# Generated by Django 5.2.5 on 2025-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='F_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='L_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='MO_no',
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(unique=True),
        ),
    ]
